# Generated by Django 4.0.4 on 2022-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pipe_id', models.IntegerField()),
            ],
        ),
    ]
